export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const EDITTING = 'EDITTING';